/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Violation = IDL.Record({
  'rule' : IDL.Text,
  'description' : IDL.Text,
  'timestamp' : Time,
});
export const TradeView = IDL.Record({
  'id' : IDL.Text,
  'rewardExpectation' : IDL.Float64,
  'stopLossSize' : IDL.Float64,
  'direction' : IDL.Text,
  'entryType' : IDL.Text,
  'entryTimestamp' : Time,
  'riskAmount' : IDL.Float64,
  'screenshotUrl' : IDL.Opt(IDL.Text),
  'pair' : IDL.Text,
  'liquiditySweepConfirmed' : IDL.Bool,
  'violations' : IDL.Vec(Violation),
  'positionSize' : IDL.Float64,
  'riskReward' : IDL.Opt(IDL.Float64),
  'newsSusceptibility' : IDL.Bool,
  'resultRR' : IDL.Opt(IDL.Float64),
  'disciplineScore' : IDL.Float64,
  'accountSize' : IDL.Float64,
  'positionSizeError' : IDL.Bool,
  'exitTimestamp' : IDL.Opt(Time),
  'isScreenshot' : IDL.Bool,
  'emotions' : IDL.Text,
  'resultPips' : IDL.Opt(IDL.Float64),
  'rewardReached' : IDL.Bool,
  'structureBreakConfirmed' : IDL.Bool,
  'positionSizeMethod' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Settings = IDL.Record({
  'baseCurrency' : IDL.Text,
  'theme' : IDL.Text,
  'strategyPresets' : IDL.Text,
  'defaultAccount' : IDL.Float64,
  'defaultRiskPercent' : IDL.Float64,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Trade = IDL.Record({
  'id' : IDL.Text,
  'rewardExpectation' : IDL.Float64,
  'stopLossSize' : IDL.Float64,
  'direction' : IDL.Text,
  'entryType' : IDL.Text,
  'entryTimestamp' : Time,
  'riskAmount' : IDL.Float64,
  'screenshotUrl' : IDL.Opt(IDL.Text),
  'pair' : IDL.Text,
  'liquiditySweepConfirmed' : IDL.Bool,
  'violations' : IDL.Vec(Violation),
  'positionSize' : IDL.Float64,
  'riskReward' : IDL.Opt(IDL.Float64),
  'newsSusceptibility' : IDL.Bool,
  'resultRR' : IDL.Opt(IDL.Float64),
  'disciplineScore' : IDL.Float64,
  'accountSize' : IDL.Float64,
  'positionSizeError' : IDL.Bool,
  'exitTimestamp' : IDL.Opt(Time),
  'isScreenshot' : IDL.Bool,
  'emotions' : IDL.Text,
  'resultPips' : IDL.Opt(IDL.Float64),
  'rewardReached' : IDL.Bool,
  'structureBreakConfirmed' : IDL.Bool,
  'positionSizeMethod' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteTrade' : IDL.Func([IDL.Text], [], []),
  'getAllTrades' : IDL.Func([], [IDL.Vec(TradeView)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getSettings' : IDL.Func([], [IDL.Opt(Settings)], ['query']),
  'getTrade' : IDL.Func([IDL.Text], [TradeView], ['query']),
  'getTradeByPair' : IDL.Func([IDL.Text], [IDL.Vec(TradeView)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveScreenshot' : IDL.Func([ExternalBlob], [ExternalBlob], []),
  'saveSettings' : IDL.Func([Settings], [], []),
  'saveTrade' : IDL.Func([Trade], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Violation = IDL.Record({
    'rule' : IDL.Text,
    'description' : IDL.Text,
    'timestamp' : Time,
  });
  const TradeView = IDL.Record({
    'id' : IDL.Text,
    'rewardExpectation' : IDL.Float64,
    'stopLossSize' : IDL.Float64,
    'direction' : IDL.Text,
    'entryType' : IDL.Text,
    'entryTimestamp' : Time,
    'riskAmount' : IDL.Float64,
    'screenshotUrl' : IDL.Opt(IDL.Text),
    'pair' : IDL.Text,
    'liquiditySweepConfirmed' : IDL.Bool,
    'violations' : IDL.Vec(Violation),
    'positionSize' : IDL.Float64,
    'riskReward' : IDL.Opt(IDL.Float64),
    'newsSusceptibility' : IDL.Bool,
    'resultRR' : IDL.Opt(IDL.Float64),
    'disciplineScore' : IDL.Float64,
    'accountSize' : IDL.Float64,
    'positionSizeError' : IDL.Bool,
    'exitTimestamp' : IDL.Opt(Time),
    'isScreenshot' : IDL.Bool,
    'emotions' : IDL.Text,
    'resultPips' : IDL.Opt(IDL.Float64),
    'rewardReached' : IDL.Bool,
    'structureBreakConfirmed' : IDL.Bool,
    'positionSizeMethod' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Settings = IDL.Record({
    'baseCurrency' : IDL.Text,
    'theme' : IDL.Text,
    'strategyPresets' : IDL.Text,
    'defaultAccount' : IDL.Float64,
    'defaultRiskPercent' : IDL.Float64,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Trade = IDL.Record({
    'id' : IDL.Text,
    'rewardExpectation' : IDL.Float64,
    'stopLossSize' : IDL.Float64,
    'direction' : IDL.Text,
    'entryType' : IDL.Text,
    'entryTimestamp' : Time,
    'riskAmount' : IDL.Float64,
    'screenshotUrl' : IDL.Opt(IDL.Text),
    'pair' : IDL.Text,
    'liquiditySweepConfirmed' : IDL.Bool,
    'violations' : IDL.Vec(Violation),
    'positionSize' : IDL.Float64,
    'riskReward' : IDL.Opt(IDL.Float64),
    'newsSusceptibility' : IDL.Bool,
    'resultRR' : IDL.Opt(IDL.Float64),
    'disciplineScore' : IDL.Float64,
    'accountSize' : IDL.Float64,
    'positionSizeError' : IDL.Bool,
    'exitTimestamp' : IDL.Opt(Time),
    'isScreenshot' : IDL.Bool,
    'emotions' : IDL.Text,
    'resultPips' : IDL.Opt(IDL.Float64),
    'rewardReached' : IDL.Bool,
    'structureBreakConfirmed' : IDL.Bool,
    'positionSizeMethod' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteTrade' : IDL.Func([IDL.Text], [], []),
    'getAllTrades' : IDL.Func([], [IDL.Vec(TradeView)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getSettings' : IDL.Func([], [IDL.Opt(Settings)], ['query']),
    'getTrade' : IDL.Func([IDL.Text], [TradeView], ['query']),
    'getTradeByPair' : IDL.Func([IDL.Text], [IDL.Vec(TradeView)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveScreenshot' : IDL.Func([ExternalBlob], [ExternalBlob], []),
    'saveSettings' : IDL.Func([Settings], [], []),
    'saveTrade' : IDL.Func([Trade], [], []),
  });
};

export const init = ({ IDL }) => { return []; };