/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface Settings {
  'baseCurrency' : string,
  'theme' : string,
  'strategyPresets' : string,
  'defaultAccount' : number,
  'defaultRiskPercent' : number,
}
export type Time = bigint;
export interface Trade {
  'id' : string,
  'rewardExpectation' : number,
  'profitLossAmount' : number,
  'stopLossSize' : number,
  'direction' : string,
  'entryType' : string,
  'entryTimestamp' : Time,
  'riskAmount' : number,
  'screenshotUrl' : [] | [string],
  'pair' : string,
  'takeProfitPrice' : number,
  'liquiditySweepConfirmed' : boolean,
  'violations' : Array<Violation>,
  'positionSize' : number,
  'riskReward' : [] | [number],
  'newsSusceptibility' : boolean,
  'resultRR' : [] | [number],
  'disciplineScore' : number,
  'accountSize' : number,
  'stopLossPrice' : number,
  'positionSizeError' : boolean,
  'grade' : [] | [string],
  'exitTimestamp' : [] | [Time],
  'isScreenshot' : boolean,
  'entryPrice' : number,
  'emotions' : string,
  'resultPips' : [] | [number],
  'rewardReached' : boolean,
  'structureBreakConfirmed' : boolean,
  'positionSizeMethod' : string,
  'winLossResult' : WinLossResult,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Violation {
  'rule' : string,
  'description' : string,
  'timestamp' : Time,
}
export type WinLossResult = { 'win' : null } |
  { 'loss' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteTrade' : ActorMethod<[string], undefined>,
  'getAllTrades' : ActorMethod<[], Array<Trade>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getSettings' : ActorMethod<[], Settings>,
  'getTrade' : ActorMethod<[string], Trade>,
  'getTradeByPair' : ActorMethod<[string], Array<Trade>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'healthCheck' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveScreenshot' : ActorMethod<[ExternalBlob], ExternalBlob>,
  'saveSettings' : ActorMethod<[Settings], undefined>,
  'saveTrade' : ActorMethod<[Trade], undefined>,
  'startFresh' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];