/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface Settings {
    baseCurrency: string;
    theme: string;
    strategyPresets: string;
    defaultAccount: number;
    defaultRiskPercent: number;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Trade {
    id: string;
    rewardExpectation: number;
    stopLossSize: number;
    direction: string;
    entryType: string;
    entryTimestamp: Time;
    riskAmount: number;
    screenshotUrl?: string;
    pair: string;
    liquiditySweepConfirmed: boolean;
    violations: Array<Violation>;
    positionSize: number;
    riskReward?: number;
    newsSusceptibility: boolean;
    resultRR?: number;
    disciplineScore: number;
    accountSize: number;
    positionSizeError: boolean;
    exitTimestamp?: Time;
    isScreenshot: boolean;
    emotions: string;
    resultPips?: number;
    rewardReached: boolean;
    structureBreakConfirmed: boolean;
    positionSizeMethod: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Violation {
    rule: string;
    description: string;
    timestamp: Time;
}
export interface UserProfile {
    name: string;
}
export interface TradeView {
    id: string;
    rewardExpectation: number;
    stopLossSize: number;
    direction: string;
    entryType: string;
    entryTimestamp: Time;
    riskAmount: number;
    screenshotUrl?: string;
    pair: string;
    liquiditySweepConfirmed: boolean;
    violations: Array<Violation>;
    positionSize: number;
    riskReward?: number;
    newsSusceptibility: boolean;
    resultRR?: number;
    disciplineScore: number;
    accountSize: number;
    positionSizeError: boolean;
    exitTimestamp?: Time;
    isScreenshot: boolean;
    emotions: string;
    resultPips?: number;
    rewardReached: boolean;
    structureBreakConfirmed: boolean;
    positionSizeMethod: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteTrade(tradeId: string): Promise<void>;
    getAllTrades(): Promise<Array<TradeView>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getSettings(): Promise<Settings | null>;
    getTrade(tradeId: string): Promise<TradeView>;
    getTradeByPair(pair: string): Promise<Array<TradeView>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveScreenshot(image: ExternalBlob): Promise<ExternalBlob>;
    saveSettings(settings: Settings): Promise<void>;
    saveTrade(trade: Trade): Promise<void>;
}
import type { ExternalBlob as _ExternalBlob, Settings as _Settings, Time as _Time, Trade as _Trade, TradeView as _TradeView, UserProfile as _UserProfile, UserRole as _UserRole, Violation as _Violation, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteTrade(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTrade(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTrade(arg0);
            return result;
        }
    }
    async getAllTrades(): Promise<Array<TradeView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTrades();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTrades();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSettings(): Promise<Settings | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSettings();
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSettings();
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTrade(arg0: string): Promise<TradeView> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrade(arg0);
                return from_candid_TradeView_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrade(arg0);
            return from_candid_TradeView_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTradeByPair(arg0: string): Promise<Array<TradeView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTradeByPair(arg0);
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTradeByPair(arg0);
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveScreenshot(arg0: ExternalBlob): Promise<ExternalBlob> {
        if (this.processError) {
            try {
                const result = await this.actor.saveScreenshot(await to_candid_ExternalBlob_n20(this._uploadFile, this._downloadFile, arg0));
                return from_candid_ExternalBlob_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveScreenshot(await to_candid_ExternalBlob_n20(this._uploadFile, this._downloadFile, arg0));
            return from_candid_ExternalBlob_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveSettings(arg0: Settings): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveSettings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveSettings(arg0);
            return result;
        }
    }
    async saveTrade(arg0: Trade): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveTrade(to_candid_Trade_n22(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveTrade(to_candid_Trade_n22(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
async function from_candid_ExternalBlob_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_TradeView_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TradeView): TradeView {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Settings]): Settings | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    rewardExpectation: number;
    stopLossSize: number;
    direction: string;
    entryType: string;
    entryTimestamp: _Time;
    riskAmount: number;
    screenshotUrl: [] | [string];
    pair: string;
    liquiditySweepConfirmed: boolean;
    violations: Array<_Violation>;
    positionSize: number;
    riskReward: [] | [number];
    newsSusceptibility: boolean;
    resultRR: [] | [number];
    disciplineScore: number;
    accountSize: number;
    positionSizeError: boolean;
    exitTimestamp: [] | [_Time];
    isScreenshot: boolean;
    emotions: string;
    resultPips: [] | [number];
    rewardReached: boolean;
    structureBreakConfirmed: boolean;
    positionSizeMethod: string;
}): {
    id: string;
    rewardExpectation: number;
    stopLossSize: number;
    direction: string;
    entryType: string;
    entryTimestamp: Time;
    riskAmount: number;
    screenshotUrl?: string;
    pair: string;
    liquiditySweepConfirmed: boolean;
    violations: Array<Violation>;
    positionSize: number;
    riskReward?: number;
    newsSusceptibility: boolean;
    resultRR?: number;
    disciplineScore: number;
    accountSize: number;
    positionSizeError: boolean;
    exitTimestamp?: Time;
    isScreenshot: boolean;
    emotions: string;
    resultPips?: number;
    rewardReached: boolean;
    structureBreakConfirmed: boolean;
    positionSizeMethod: string;
} {
    return {
        id: value.id,
        rewardExpectation: value.rewardExpectation,
        stopLossSize: value.stopLossSize,
        direction: value.direction,
        entryType: value.entryType,
        entryTimestamp: value.entryTimestamp,
        riskAmount: value.riskAmount,
        screenshotUrl: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.screenshotUrl)),
        pair: value.pair,
        liquiditySweepConfirmed: value.liquiditySweepConfirmed,
        violations: value.violations,
        positionSize: value.positionSize,
        riskReward: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.riskReward)),
        newsSusceptibility: value.newsSusceptibility,
        resultRR: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.resultRR)),
        disciplineScore: value.disciplineScore,
        accountSize: value.accountSize,
        positionSizeError: value.positionSizeError,
        exitTimestamp: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.exitTimestamp)),
        isScreenshot: value.isScreenshot,
        emotions: value.emotions,
        resultPips: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.resultPips)),
        rewardReached: value.rewardReached,
        structureBreakConfirmed: value.structureBreakConfirmed,
        positionSizeMethod: value.positionSizeMethod
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TradeView>): Array<TradeView> {
    return value.map((x)=>from_candid_TradeView_n11(_uploadFile, _downloadFile, x));
}
async function to_candid_ExternalBlob_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_Trade_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Trade): _Trade {
    return to_candid_record_n23(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    rewardExpectation: number;
    stopLossSize: number;
    direction: string;
    entryType: string;
    entryTimestamp: Time;
    riskAmount: number;
    screenshotUrl?: string;
    pair: string;
    liquiditySweepConfirmed: boolean;
    violations: Array<Violation>;
    positionSize: number;
    riskReward?: number;
    newsSusceptibility: boolean;
    resultRR?: number;
    disciplineScore: number;
    accountSize: number;
    positionSizeError: boolean;
    exitTimestamp?: Time;
    isScreenshot: boolean;
    emotions: string;
    resultPips?: number;
    rewardReached: boolean;
    structureBreakConfirmed: boolean;
    positionSizeMethod: string;
}): {
    id: string;
    rewardExpectation: number;
    stopLossSize: number;
    direction: string;
    entryType: string;
    entryTimestamp: _Time;
    riskAmount: number;
    screenshotUrl: [] | [string];
    pair: string;
    liquiditySweepConfirmed: boolean;
    violations: Array<_Violation>;
    positionSize: number;
    riskReward: [] | [number];
    newsSusceptibility: boolean;
    resultRR: [] | [number];
    disciplineScore: number;
    accountSize: number;
    positionSizeError: boolean;
    exitTimestamp: [] | [_Time];
    isScreenshot: boolean;
    emotions: string;
    resultPips: [] | [number];
    rewardReached: boolean;
    structureBreakConfirmed: boolean;
    positionSizeMethod: string;
} {
    return {
        id: value.id,
        rewardExpectation: value.rewardExpectation,
        stopLossSize: value.stopLossSize,
        direction: value.direction,
        entryType: value.entryType,
        entryTimestamp: value.entryTimestamp,
        riskAmount: value.riskAmount,
        screenshotUrl: value.screenshotUrl ? candid_some(value.screenshotUrl) : candid_none(),
        pair: value.pair,
        liquiditySweepConfirmed: value.liquiditySweepConfirmed,
        violations: value.violations,
        positionSize: value.positionSize,
        riskReward: value.riskReward ? candid_some(value.riskReward) : candid_none(),
        newsSusceptibility: value.newsSusceptibility,
        resultRR: value.resultRR ? candid_some(value.resultRR) : candid_none(),
        disciplineScore: value.disciplineScore,
        accountSize: value.accountSize,
        positionSizeError: value.positionSizeError,
        exitTimestamp: value.exitTimestamp ? candid_some(value.exitTimestamp) : candid_none(),
        isScreenshot: value.isScreenshot,
        emotions: value.emotions,
        resultPips: value.resultPips ? candid_some(value.resultPips) : candid_none(),
        rewardReached: value.rewardReached,
        structureBreakConfirmed: value.structureBreakConfirmed,
        positionSizeMethod: value.positionSizeMethod
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
